branches:
  only:
    - next
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack and Build"
      os: osx
      env:
        - Platform="iOS"
        - Xcode="9.2"
        - Webpack="true"
      osx_image: xcode9.2
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      before_script:
        - cd demo && tns platform add ios@next
      script: npm run build.plugin && npm i && tns build ios --bundle --env.uglify
    - os: linux
      language: android
      env:
        - Platform="Android"
        - AndroidSDK="26"
        - Webpack="true"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      before_script:
        - cd demo && tns platform add android@next
      script: >
        echo { \"project_info\": { \"project_number\": \"424050927453\", \"firebase_url\": \"https://pptest-53916.firebaseio.com\", \"project_id\": \"pptest-53916\", \"storage_bucket\": \"pptest-53916.appspot.com\" }, \"client\": [ { \"client_info\": { \"mobilesdk_app_id\": \"1:424050927453:android:21d2dd8987e1e3d1\", \"android_client_info\": { \"package_name\": \"org.nativescript.ppTest\" } }, \"oauth_client\": [ { \"client_id\": \"424050927453-o7gv6bcmknujjoaaoa5r4d452cutb9jf.apps.googleusercontent.com\", \"client_type\": 3 } ], \"api_key\": [ { \"current_key\": \"AIzaSyDr3fqH7Z8-vhBNpAges_KFTA7oOoylGvU\" } ], \"services\": { \"analytics_service\": { \"status\": 1 }, \"appinvite_service\": { \"status\": 1, \"other_platform_oauth_client\": [] }, \"ads_service\": { \"status\": 2 } } } ], \"configuration_version\": \"1\"} > ../demo/app/App_Resources/Android/google-services.json && npm run build.plugin && npm i && tns build android --bundle --env.uglify
    - language: android
      env:
        - Platform="Android"
        - AndroidSDK="26"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      before_script:
        - cd demo && tns platform add android@next
      script: >
        echo { \"project_info\": { \"project_number\": \"424050927453\", \"firebase_url\": \"https://pptest-53916.firebaseio.com\", \"project_id\": \"pptest-53916\", \"storage_bucket\": \"pptest-53916.appspot.com\" }, \"client\": [ { \"client_info\": { \"mobilesdk_app_id\": \"1:424050927453:android:21d2dd8987e1e3d1\", \"android_client_info\": { \"package_name\": \"org.nativescript.ppTest\" } }, \"oauth_client\": [ { \"client_id\": \"424050927453-o7gv6bcmknujjoaaoa5r4d452cutb9jf.apps.googleusercontent.com\", \"client_type\": 3 } ], \"api_key\": [ { \"current_key\": \"AIzaSyDr3fqH7Z8-vhBNpAges_KFTA7oOoylGvU\" } ], \"services\": { \"analytics_service\": { \"status\": 1 }, \"appinvite_service\": { \"status\": 1, \"other_platform_oauth_client\": [] }, \"ads_service\": { \"status\": 2 } } } ], \"configuration_version\": \"1\"} > ../demo/app/App_Resources/Android/google-services.json &&
        npm run ci.android.build
    - os: osx
      env:
        - Platform="iOS"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      before_script:
        - cd demo && tns platform add ios@next
      script: npm run ci.ios.build

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-23
    - android-26
    - extra-android-m2repository

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src
    - npm uninstall tns-core-modules -D && npm install tns-core-modules@next -D
    - npm uninstall nativescript-angular -D && npm install nativescript-angular@next -D
    - cd ../demo
    - npm run build.plugin
    - npm uninstall tns-core-modules -P && npm install tns-core-modules@next -P
    - npm uninstall nativescript-dev-webpack -D && npm install nativescript-dev-webpack@next -D
    - npm uninstall nativescript-dev-typescript -D && npm install nativescript-dev-typescript@next -D
    - cd ..